services:
  db:
    image: postgres:15.13
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: test
      POSTGRES_DB: diary_db
    ports:
      - "5432:5432"





